/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,jsx}",
    "./components/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface": "#e5e2e1",
        "secondary-container": "#474746",
        "inverse-on-surface": "#313030",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary-fixed-variant": "#454747",
        "surface-dim": "#131313",
        "surface-container": "#201f1f",
        "primary-fixed": "#d97706",
        "primary-fixed-dim": "#d97706",
        "surface-variant": "#353534",
        "on-primary-fixed-variant": "#92400e",
        "on-secondary-fixed-variant": "#474746",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary": "#2f3131",
        "inverse-surface": "#e5e2e1",
        "surface-container-high": "#2a2a2a",
        "on-surface-variant": "#c0caad",
        "on-primary-fixed": "#ffffff",
        "secondary": "#c8c6c5",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#c8c6c5",
        "outline": "#8a947a",
        "inverse-primary": "#d97706",
        "surface-container-low": "#1c1b1b",
        "surface": "#131313",
        "on-error-container": "#ffdad6",
        "error-container": "#93000a",
        "primary": "#ffffff",
        "tertiary": "#ffffff",
        "on-error": "#690005",
        "on-secondary": "#313030",
        "background": "#131313",
        "surface-tint": "#d97706",
        "surface-container-highest": "#353534",
        "on-tertiary-container": "#636565",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary-fixed": "#1a1c1c",
        "primary-container": "#d97706",
        "surface-bright": "#3a3939",
        "on-secondary-fixed": "#1c1b1b",
        "on-primary-container": "#ffffff",
        "outline-variant": "#414a34",
        "tertiary-container": "#e2e2e2",
        "error": "#ffb4ab",
        "on-background": "#e5e2e1",
        "on-secondary-container": "#b7b5b4",
        "tertiary-fixed-dim": "#c6c6c7",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        base: "8px",
        gutter: "24px",
        "container-max": "1280px",
        "margin-desktop": "64px",
      },
      fontFamily: {
        "body-md": ["var(--font-outfit)", "sans-serif"],
        "headline-md": ["var(--font-montserrat)", "sans-serif"],
        "label-md": ["var(--font-outfit)", "sans-serif"],
        "headline-xl": ["var(--font-montserrat)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-montserrat)", "sans-serif"],
        "headline-lg": ["var(--font-montserrat)", "sans-serif"],
        "body-lg": ["var(--font-outfit)", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-md": [
          "14px",
          { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-xl": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "headline-lg-mobile": [
          "32px",
          { lineHeight: "1.2", fontWeight: "700" },
        ],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      animation: {
        "pulse-whatsapp": "pulse-green 2s infinite",
      },
      keyframes: {
        "pulse-green": {
          "0%": { boxShadow: "0 0 0 0 rgba(217, 119, 6, 0.7)" },
          "70%": { boxShadow: "0 0 0 15px rgba(217, 119, 6, 0)" },
          "100%": { boxShadow: "0 0 0 0 rgba(217, 119, 6, 0)" },
        },
      },
    },
  },
  plugins: [],
};
